# Generated by Django 3.1.6 on 2022-03-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weirdosostoriesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='title_tag',
            field=models.CharField(default='Weirdoso Stories', max_length=255),
        ),
    ]
