# Generated by Django 3.1.6 on 2022-03-06 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weirdosostoriesapp', '0002_bookpost_title_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpost',
            name='title_tag',
        ),
    ]
