# Generated by Django 3.2.12 on 2022-04-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weirdosostoriesapp', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
