# Generated by Django 3.1.6 on 2022-04-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weirdosostoriesapp', '0012_auto_20220405_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='bookpost',
            name='wattpad_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
