# Generated by Django 3.1.6 on 2022-04-29 15:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weirdosostoriesapp', '0016_alter_bookpost_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpost',
            name='likes',
            field=models.ManyToManyField(related_name='book_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
