# Generated by Django 3.1.6 on 2022-05-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weirdosostoriesapp', '0017_auto_20220429_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('bookpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='weirdosostoriesapp.bookpost')),
            ],
        ),
    ]
