# Generated by Django 3.2.12 on 2022-06-02 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weirdosostoriesapp', '0019_auto_20220602_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='title',
            new_name='emailaddress',
        ),
    ]
